---

- name: Set up intial environment
  hosts: all
  user: root
  gather_facts: no

  roles:
    - base_setting


- name: Set up M/W Cluster environment
  hosts: MiddleWare
  user: root
  
  roles:
    - mw_setting


- name: Set up Head & Compute Cluster environment
  hosts: Head_Compute
  user: root

  roles:
    - head_compute


- name: Set up Head Cluster environment
  hosts: Head
  user: root

  roles:
    - head_setting


- name: Set up Compute Cluster environment
  hosts: Compute
  user: root

  roles:
    - compute_setting
