---

- name: Copy cookie file
  copy: src=oracle dest={{ path }}

- name: Download Java SE Development Kit 8
  shell: wget -O "{{ path }}/jdk-8u11-linux-x64.rpm" --load-cookies="{{ path }}/oracle" http://download.oracle.com/otn-pub/java/jdk/8u11-b12/jdk-8u11-linux-x64.rpm --no-check-certificate

- name: Install JDK 8
  yum: name="{{ path }}/jdk-8u11-linux-x64.rpm" state=present

- name: Configure the OS to use SUN JDK 8 ...(1)
  shell: alternatives --install /usr/bin/java java /usr/java/jdk1.8.0_11/jre/bin/java 20000

- name:  Configure the OS to use SUN JDK 8 ...(2)
  shell: alternatives --install /usr/bin/javaws javaws /usr/java/jdk1.8.0_11/jre/bin/javaws 20000

- name:  Configure the OS to use SUN JDK 8 ...(3)
  shell: alternatives --install /usr/bin/javac javac /usr/java/jdk1.8.0_11/bin/javac 20000

- name:  Configure the OS to use SUN JDK 8 ...(4)
  shell: alternatives --install /usr/bin/jar jar /usr/java/jdk1.8.0_11/bin/jar 20000

- name:  Configure the OS to use SUN JDK 8 ...(5)
  shell: alternatives --set java /usr/java/jdk1.8.0_11/jre/bin/java

- name:  Configure the OS to use SUN JDK 8 ...(6)
  shell: alternatives --set javaws /usr/java/jdk1.8.0_11/jre/bin/javaws

- name:  Configure the OS to use SUN JDK 8 ...(7)
  shell: alternatives --set javac /usr/java/jdk1.8.0_11/bin/javac

- name:  Configure the OS to use SUN JDK 8 ...(8)
  shell: alternatives --set jar /usr/java/jdk1.8.0_11/bin/jar

- name: Register JAVA_HOME path
  shell: echo "export JAVA_HOME=/usr/java/jdk1.8.0_11" >> /root/.bashrc

- name: Register JRE_HOME path
  shell: echo "export JRE_HOME=/usr/java/jdk1.8.0_11" >> /root/.bashrc

- name: Reload environment variable
  shell: source /root/.bashrc
